fix: issues with npm run start
db-ui/mono pull request #111
Opened 2022-12-15 14:41 UTC by nmerget

2022-12-15 14:57 UTC, mfranzke requested changes

2022-12-15 14:57 UTC, mfranzke commented on showcases/angular-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations",
Is there  a typo in the path ("packagesi"), and in the other files as well ?

2022-12-15 18:14 UTC, mfranzke commented on showcases/react-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations",
@nmerget Is there a typo in the path ("packagesi"), and in the other files as well ?
```suggestion
    "@db-ui/foundations": "file:../../packages/foundations",
```

2022-12-15 18:14 UTC, mfranzke commented on showcases/svelte-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations"
@nmerget Is there a typo in the path ("packages**i**")?
```suggestion
    "@db-ui/foundations": "file:../../packages/foundations"
```

2022-12-15 18:15 UTC, mfranzke commented on showcases/vanilla-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations"
@nmerget Is there a typo in the path ("packages**i**")?
```suggestion
    "@db-ui/foundations": "file:../../packages/foundations"
```

2022-12-15 18:15 UTC, mfranzke commented on showcases/vue-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations",
@nmerget Is there a typo in the path ("packages**i**")?
```suggestion
    "@db-ui/foundations": "file:../../packages/foundations",
```

2022-12-15 18:16 UTC, mfranzke commented on showcases/next-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations",
@nmerget Is there a typo in the path ("packages**i**")?
```suggestion
    "@db-ui/foundations": "file:../../packages/foundations",
```

2022-12-15 18:17 UTC, mfranzke commented on showcases/angular-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations",
@nmerget Is there a typo in the path ("packages**i**")?
```suggestion
    "@db-ui/foundations": "file:../../packages/foundations",
```

2022-12-16 07:25 UTC, nmerget commented on showcases/react-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations",
fixed

2022-12-16 07:25 UTC, nmerget commented on showcases/next-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations",
fixed

2022-12-16 07:25 UTC, nmerget commented on showcases/angular-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations",
fixed

2022-12-16 07:26 UTC, nmerget commented on showcases/vue-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations",
fixed

2022-12-16 07:26 UTC, nmerget commented on showcases/svelte-showcase/package.json
> +    "@db-ui/foundations": "file:../../packagesi/foundations"
fixed

2022-12-16 07:30 UTC, mfranzke approved these changes

2022-12-16 07:30 UTC, merged