Feat cicd
db-ui/mono pull request #20
Opened 2022-12-06 14:00 UTC by nmerget

2022-12-08 07:00 UTC, nmerget commented on .github/workflows/01-build-packages.yml
> +      - name: 🧹 Clean node_modules and assets
fixed

2022-12-09 13:52 UTC, mfranzke requested changes

2022-12-09 13:52 UTC, mfranzke commented on package.json
> +    "lint:xo": "xo --fix",
this isn't relevant for the pipeline, but would lead to a changed file during commit process on localhost – is this what you're targeting at ?

2022-12-09 13:52 UTC, mfranzke commented on .github/workflows/release.yml
> +  publishpackages:
naming: you've used a dash for word separation in the names before

2022-12-09 13:56 UTC, mfranzke commented on package.json
> +  "name": "@db-ui/mono",
what does the root package contain that we would actually be publishing (in combination with line 85: `"access": "public"`)

2022-12-09 14:28 UTC, nmerget commented on .github/workflows/default.yml
> +#    needs: [cypress]
Maybe you should close your tabs sometimes or reload the page while doing a review haha, I did it already ;)

2022-12-09 14:29 UTC, nmerget commented on package.json
> +    "lint:xo": "xo --fix",
I had a lot of issues with the line endings CSLF and LF and xo rejected the commit all the time. I think we can use --fix here if we trust xo

2022-12-09 14:32 UTC, nmerget commented on package.json
> +  "name": "@db-ui/mono",
We won't publish from the root monorepo, the reason is that we have the workspaces for all output targets inside the packages/components. For deployment, I created another directory build-outputs to separate the publishing process.

2022-12-09 14:34 UTC, nmerget commented on packages/foundations/tokens/screens.json
> +			"value": "40",
I had to change this to rem values because for our new foundation targets (compose and ios-swift) we need to use rem to calculate the correct size.

Is it important to use those in web with px values?

2022-12-09 14:34 UTC, nmerget commented on showcases/angular-showcase/angular.json
> +									"maximumError": "20kb"
Those are the assets like .css which are causing problems

2022-12-09 14:38 UTC, nmerget commented on .github/workflows/03-deploy-gh-pages.yml
> +            echo "##[set-output name=name;]$(echo $BRANCH_NAME)"
fixed

2022-12-09 14:38 UTC, nmerget commented on .github/workflows/release.yml
> +  publishpackages:
fixed

2022-12-09 15:09 UTC, mfranzke commented on packages/foundations/tokens/screens.json
> +			"value": "40",
This is somehow more of a conceptual question, because the main difference is regarding whether those should change in case that only the text-size gets increased by browser settings vs. the zoom functionality is actually being used (e.g. in Firefox: "Zoom text only").

2022-12-09 15:10 UTC, mfranzke commented on package.json
> +    "lint:xo": "xo --fix",
I actually **love** XO

2022-12-09 15:11 UTC, mfranzke approved these changes

2022-12-09 15:11 UTC, merged