feat: unified showcases
db-ui/mono pull request #303
Opened 2023-01-30 16:04 UTC by nmerget

2023-02-08 06:15 UTC, mfranzke commented
@nmerget some of the CSS fail to load within the vanilla showcase:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/787658/217449744-3ff72397-a7de-4d89-bfc3-3f66dfef32e8.png">

2023-02-08 15:59 UTC, mfranzke requested changes

2023-02-08 15:59 UTC, mfranzke commented on packages/components/src/components/button/button.spec.tsx
> +				asdf
```suggestion
				lorem ipsum
```

2023-02-08 15:59 UTC, mfranzke commented on packages/foundations/scss/_tonality.scss
> +	--db-base-font-size: var(--db-type-body-font-size-#{$size});
see review for `packages/foundations/scss/helpers/_shadow-dom.scss`

2023-02-08 16:07 UTC, mfranzke requested changes

2023-02-08 16:07 UTC, mfranzke commented on packages/components/_templates/mitosis/new/scss.ejs.t
> +}
see review for `packages/foundations/scss/helpers/_shadow-dom.scss`

2023-02-08 16:07 UTC, mfranzke commented on showcases/angular-showcase/src/app/components/form/form.component.html
> +		<form>
```suggestion
	<form>
		<fieldset>
```

forms needs to surround `fieldset` elements and forms even also need to contain a `button` (at least we want to provide "good examples".

2023-02-08 16:07 UTC, mfranzke commented on showcases/angular-showcase/src/app/components/form/form.component.html
> +		</form>
```suggestion
```

2023-02-08 16:07 UTC, mfranzke commented on showcases/angular-showcase/src/app/components/form/form.component.html
> +	</fieldset>
```suggestion
```

2023-02-08 16:07 UTC, mfranzke commented on showcases/angular-showcase/src/app/components/form/form.component.html
> +		</DBButton>
```suggestion
		</DBButton>	</fieldset>		</form>
```

2023-02-08 16:07 UTC, mfranzke commented on showcases/react-showcase/src/components/form/index.tsx
> +					<form>
see feedback within `showcases/angular-showcase/src/app/components/form/form.component.html`

2023-02-08 16:07 UTC, mfranzke commented on showcases/vanilla-showcase/src/components/form/index.js
> +			<form>
see feedback within `showcases/angular-showcase/src/app/components/form/form.component.html`

2023-02-08 16:07 UTC, mfranzke commented on showcases/vue-showcase/src/components/form/Form.vue
> +				<form>
see feedback within `showcases/angular-showcase/src/app/components/form/form.component.html`

2023-02-09 06:49 UTC, nmerget commented on showcases/angular-current-showcase/angular.json
> +									"maximumError": "5mb"
I had to add this, because of the colors I use. The file of color-classes.scss is quite big. But it's not a big deal to increase this value here

2023-02-09 06:49 UTC, nmerget commented on showcases/angular-lts-showcase/angular.json
> +									"maximumError": "5mb"
https://github.com/db-ui/mono/pull/303#discussion_r1101040832

2023-02-09 07:32 UTC, nmerget commented on packages/foundations/scss/helpers/_shadow-dom.scss
> +}
I don't know what you think about it. Do you have another solution for it?

On all the other frameworks we have `:root * {}` for setting the line-height and font-size.

But the issue with shadow-dom is (example button) that the font size and line-height are overwritten by the default button styles. So I need to add them extra inside of the shadow dom somehow.

If you have a better solution, feel free to add it

2023-02-09 07:50 UTC, mfranzke commented on packages/foundations/scss/helpers/_shadow-dom.scss
> +	font-size: var(--db-base-font-size);
```suggestion
	line-height: inherit;
    font-size: inherit;
    font-family: inherit;
```

2023-02-10 11:27 UTC, mfranzke approved these changes

2023-02-10 11:31 UTC, merged