feat: add infotext component
db-ui/mono pull request #372
Opened 2023-02-08 12:46 UTC by nmerget

2023-02-09 16:07 UTC, mfranzke commented on packages/components/src/components/infotext/model.ts
> +	variant?: 'adaptive' | 'critical' | 'information' | 'warning' | 'success'; // TODO: Move this to global props
could you want to do this "move" now or do you want to do it later ?

2023-02-09 16:15 UTC, mfranzke submitted a review, later dismissed

2023-02-09 16:15 UTC, mfranzke commented on packages/components/src/components/infotext/infotext.scss
> +		}
you could as well define key/value pairs on line 5 and that for use a simple each than here:
https://sass-lang.com/documentation/values/maps#do-something-for-every-pair

2023-02-09 16:15 UTC, mfranzke commented on packages/components/src/components/infotext/infotext.lite.tsx
> +		<div
Is this really supposed to be a block level element, or isn't it inline?

```suggestion
		<span
```

2023-02-09 16:15 UTC, mfranzke commented on packages/components/src/components/infotext/infotext.lite.tsx
> +		</div>
```suggestion
		</span>
```

2023-02-09 16:15 UTC, mfranzke commented on packages/components/src/components/infotext/infotext.lite.tsx
> +					return 'info';
let's align with the colleagues whether this mapping is even also a global one, that we could persist at a more global place ?

2023-02-09 20:41 UTC, annsch commented on packages/components/src/components/infotext/infotext.lite.tsx
> +		<div
@mfranzke I had the same question when implementing this for RI UI. In case of RI UI (for example) we need this to be a block element. We could discuss if this could be a data attribute as well?

2023-02-10 09:21 UTC, mfranzke requested changes

2023-02-10 09:21 UTC, mfranzke commented on packages/foundations/scss/_body-styles.scss
> +	font-size: var(--db-type-body-font-size-#{$size});
why do you both set variables as well as declarations (instead of e.g. only variables, and the `line-height` and `font-size` only once at a global level / selector)? This part seems to be that global and separate from infotext, that it might be a good candidate for a separate PR (with a description).

2023-02-10 11:03 UTC, nmerget commented on packages/foundations/scss/_body-styles.scss
> +	font-size: var(--db-type-body-font-size-#{$size});
https://github.com/db-ui/mono/pull/397

2023-02-14 07:22 UTC, mfranzke submitted a review, later dismissed

2023-02-14 09:28 UTC, mfranzke approved these changes

2023-02-14 09:28 UTC, merged