chore: update docs for button
db-ui/mono pull request #837
Opened 2023-04-12 11:14 UTC by nmerget

2023-04-12 15:24 UTC, mfranzke commented on packages/components/README.md
> -
As you've removed these, I'm not sure where you wanted to put them instead.

2023-04-12 15:29 UTC, mfranzke commented on packages/components/src/components/button/button.spec.tsx
> +		await mount(<DBButton icon="account">lorem ipsum</DBButton>);
```suggestion
		await mount(<DBButton icon="account" icntxt="true">lorem ipsum</DBButton>);
```

As this is the "icon only" testcase, wouldn't it need that attribute instead of removing it altogether?

2023-04-13 05:41 UTC, nmerget commented on packages/components/src/components/button/button.spec.tsx
> +		await mount(<DBButton icon="account">lorem ipsum</DBButton>);
The default with a icon button is without text. So `icntxt` is false and shouldn't be used

2023-04-13 06:04 UTC, nmerget commented on packages/components/README.md
> -
Add new PR for this: https://github.com/db-ui/mono/pull/841

2023-04-13 08:46 UTC, mfranzke commented on packages/components/src/components/button/button.spec.tsx
> +		await mount(<DBButton icon="account">lorem ipsum</DBButton>);
A button without a visible text is more problematic regarding accessibility, as an element should always contain a visual textual description e.g. for voice control. That for I would expect that having an icon as an additional part of button with a visible text would be the default, and as this isn't clearly defined within the specification, I would at least interpret the order of the elements within Zeplin as well as within Marketingportal that Icon with text would be the default: https://marketingportal.extranet.deutschebahn.com/marketingportal/Design-Anwendungen/db-ux-design-system-v3/components/action/button#:~:text=Handlungsaufforderung%20zu%20beeintr%C3%A4chtigen.-,Content,-(Default)%20Text

2023-04-13 11:08 UTC, nmerget commented on packages/components/src/components/button/button.spec.tsx
> +		await mount(<DBButton icon="account">lorem ipsum</DBButton>);
changed the default behaviour

2023-04-13 12:24 UTC, mfranzke commented on packages/components/src/components/button/model.ts
> +	 * Width of the button. Auto width based on text size, full width based on parent width.
👮‍♀️

2023-04-13 14:07 UTC, nmerget commented on packages/components/src/components/button/model.ts
> +	 * Width of the button. Auto width based on text size, full width based on parent elements width.
?

2023-04-13 14:14 UTC, mfranzke commented on packages/components/src/components/button/model.ts
> +	 * Width of the button. Auto width based on text size, full width based on parent elements width.
the `variant` property has the same comment / description like the `width` property.

2023-04-13 14:28 UTC, mfranzke requested changes
![image](https://user-images.githubusercontent.com/787658/231790938-6ba636c4-4d8b-4084-814d-daf0b8f92d5e.png)
The buttons contents aren't horizontally centered within [this branch](https://db-ui.github.io/mono/review/docs-button/components/button) anymore – on [main](https://db-ui.github.io/mono/review/main/components/button) it's still centered.

2023-04-13 14:32 UTC, mfranzke commented on packages/components/src/components/button/button.lite.tsx
> +			data-icon={state.iconVisible(props.icon) && props.icon}
![image](https://user-images.githubusercontent.com/787658/231792539-b88c93ca-be1a-4b23-9cf7-2631452696c3.png)

The buttons contents aren't horizontally centered within [this branch](https://db-ui.github.io/mono/review/docs-button/components/button) anymore – on [main](https://db-ui.github.io/mono/review/main/components/button) it's still centered.

This seems to be related to the aspect, that data-icon="false" is currently set to buttons, even though that this is not a valid value and that attribute shouldn't get set at all in this case.

2023-04-13 15:03 UTC, nmerget commented on packages/components/src/components/button/model.ts
> +	 * Width of the button. Auto width based on text size, full width based on parent elements width.
oh good catch

2023-04-13 15:09 UTC, nmerget commented on packages/components/src/components/button/button.lite.tsx
> +			data-icon={state.iconVisible(props.icon) && props.icon}
fixed

2023-04-13 15:13 UTC, mfranzke submitted a review, later dismissed

2023-04-13 15:22 UTC, merged